version: '3'
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
  web:
    build: .
    image: rails_template:latest
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
  js:
    image: rails_template:latest
    command: yarn build --watch
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
  css:
    image: rails_template:latest
    command: yarn build:css --watch
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
volumes:
  db:
  bundle:
  node_modules:
